name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: windows-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        options: >-
          --health-cmd "curl -f http://localhost:4566/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        run: |
          echo "Waiting for LocalStack to be ready..."
          for i in {1..10}; do
            if curl -f http://localhost:4566/health; then
              echo "LocalStack is ready"
              break
            else
              echo "Waiting for LocalStack..."
              sleep 3
            fi
          done
          terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        run: terraform plan

      - name: Apply Terraform (Only on main branch)
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        run: terraform apply -auto-approve